package holons

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	holonsv1 "github.com/organic-programming/go-holons/gen/go/holons/v1"
	"github.com/organic-programming/grace-op/internal/progress"
)

func TestGenerateDescribeSourceSkipsWhenTemplateMissing(t *testing.T) {
	root := t.TempDir()
	dir := writeProtoCargoHolonFixture(t, root, "no-template-cargo")

	manifest, err := LoadManifest(dir)
	if err != nil {
		t.Fatalf("LoadManifest failed: %v", err)
	}

	restore, err := generateDescribeSource(manifest, progress.Silence())
	if err != nil {
		t.Fatalf("generateDescribeSource returned error: %v", err)
	}
	t.Cleanup(restore)

	matches, err := filepath.Glob(filepath.Join(dir, "gen", "describe_generated.*"))
	if err != nil {
		t.Fatalf("glob generated files: %v", err)
	}
	if len(matches) != 0 {
		t.Fatalf("expected no generated describe sources, found %v", matches)
	}
}

func TestExecuteLifecycleBuildFailsWhenDescribeTemplateCannotRender(t *testing.T) {
	if _, err := execLookPath("go"); err != nil {
		t.Skip("go command not available")
	}

	root := t.TempDir()
	chdirForHolonTest(t, root)
	dir := writeProtoGoHolonFixture(t, root, "bad-describe-template")
	writeGoDescribeTemplate(t, root, "{{")

	_, err := ExecuteLifecycle(OperationBuild, dir)
	if err == nil {
		t.Fatal("expected build to fail")
	}
	if !strings.Contains(err.Error(), "describe source") {
		t.Fatalf("error should mention describe source, got %v", err)
	}

	if _, statErr := os.Stat(filepath.Join(dir, "gen", "describe_generated.go")); !os.IsNotExist(statErr) {
		t.Fatalf("generated describe source should not exist after failure: %v", statErr)
	}
}

func TestExecuteLifecycleBuildGeneratesDescribeSource(t *testing.T) {
	if _, err := execLookPath("go"); err != nil {
		t.Skip("go command not available")
	}

	root := t.TempDir()
	chdirForHolonTest(t, root)
	dir := writeProtoGoHolonFixture(t, root, "describe-source-build")
	copyRepoGoDescribeTemplate(t, root)
	writeDescribeProtoFixture(t, dir)

	_, err := ExecuteLifecycle(OperationBuild, dir)
	if err != nil {
		t.Fatalf("build failed: %v", err)
	}

	outputPath := filepath.Join(dir, "gen", "describe_generated.go")
	data, err := os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("read generated describe source: %v", err)
	}

	content := string(data)
	if !strings.Contains(content, "Code generated by op build. DO NOT EDIT.") {
		t.Fatal("generated describe source missing header")
	}
	if !strings.Contains(content, "func StaticDescribeResponse() *holonsv1.DescribeResponse") {
		t.Fatal("generated describe source missing StaticDescribeResponse")
	}
	if !strings.Contains(content, "test.v1.Echo") {
		t.Fatal("generated describe source missing service name")
	}
}

func TestExecuteLifecycleBuildGeneratesDescribeSourceFromAPIV1Layout(t *testing.T) {
	if _, err := execLookPath("go"); err != nil {
		t.Skip("go command not available")
	}

	root := t.TempDir()
	chdirForHolonTest(t, root)
	dir := writeProtoGoHolonFixture(t, root, "describe-source-api-layout")
	copyRepoGoDescribeTemplate(t, root)
	writeDescribeAPIProtoFixture(t, dir)

	_, err := ExecuteLifecycle(OperationBuild, dir)
	if err != nil {
		t.Fatalf("build failed: %v", err)
	}

	outputPath := filepath.Join(dir, "gen", "describe_generated.go")
	data, err := os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("read generated describe source: %v", err)
	}

	content := string(data)
	if !strings.Contains(content, "test.v1.Echo") {
		t.Fatal("generated describe source missing api/v1 service name")
	}
}

func TestRenderDescribeTemplateFromGoSDKCompiles(t *testing.T) {
	if _, err := execLookPath("go"); err != nil {
		t.Skip("go command not available")
	}

	root := t.TempDir()
	outputPath := filepath.Join(root, "gen", "describe_generated.go")

	rendered, err := renderDescribeTemplate(repoGoDescribeTemplatePath(t), outputPath, sampleDescribeResponse())
	if err != nil {
		t.Fatalf("renderDescribeTemplate failed: %v", err)
	}

	content := string(rendered)
	if !strings.Contains(content, "Code generated by op build. DO NOT EDIT.") {
		t.Fatal("rendered output missing generated header")
	}
	if !strings.Contains(content, "func StaticDescribeResponse() *holonsv1.DescribeResponse") {
		t.Fatal("rendered output missing StaticDescribeResponse")
	}
	if !strings.Contains(content, "test.v1.Echo") {
		t.Fatal("rendered output missing service name")
	}
	if !strings.Contains(content, "FieldLabel_FIELD_LABEL_MAP") {
		t.Fatal("rendered output missing map field label")
	}

	if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil {
		t.Fatalf("mkdir gen: %v", err)
	}
	if err := os.WriteFile(outputPath, rendered, 0o644); err != nil {
		t.Fatalf("write generated source: %v", err)
	}
	if err := os.WriteFile(filepath.Join(root, "go.mod"), []byte(compilationModuleFile(t)), 0o644); err != nil {
		t.Fatalf("write go.mod: %v", err)
	}

	output, err := runCommand(root, []string{"go", "mod", "tidy"})
	if err != nil {
		t.Fatalf("go mod tidy failed: %v\n%s", err, output)
	}

	output, err = runCommand(root, []string{"go", "test", "./gen"})
	if err != nil {
		t.Fatalf("go test ./gen failed: %v\n%s", err, output)
	}
}

func writeGoDescribeTemplate(t *testing.T, root, contents string) {
	t.Helper()

	path := filepath.Join(root, "sdk", "go-holons", "templates", "describe.go.tmpl")
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("mkdir template dir: %v", err)
	}
	if err := os.WriteFile(path, []byte(contents), 0o644); err != nil {
		t.Fatalf("write template: %v", err)
	}
}

func copyRepoGoDescribeTemplate(t *testing.T, root string) {
	t.Helper()

	data, err := os.ReadFile(repoGoDescribeTemplatePath(t))
	if err != nil {
		t.Fatalf("read repo template: %v", err)
	}
	writeGoDescribeTemplate(t, root, string(data))
}

func repoGoDescribeTemplatePath(t *testing.T) string {
	t.Helper()
	return filepath.Join(holonsRepoRoot(t), "sdk", "go-holons", "templates", "describe.go.tmpl")
}

func writeDescribeProtoFixture(t *testing.T, dir string) {
	t.Helper()

	protoPath := filepath.Join(dir, "proto", "test", "v1", "echo.proto")
	if err := os.MkdirAll(filepath.Dir(protoPath), 0o755); err != nil {
		t.Fatalf("mkdir proto dir: %v", err)
	}

	const source = `syntax = "proto3";

package test.v1;

// Echo responds with the request payload for describe generation tests.
service Echo {
  // Ping echoes the inbound message.
  // @example {"message":"hello"}
  rpc Ping(PingRequest) returns (PingResponse);
}

message PingRequest {
  // Message to echo back.
  // @required
  // @example "hello"
  string message = 1;
}

message PingResponse {
  // Message returned by the service.
  string message = 1;
}
`
	if err := os.WriteFile(protoPath, []byte(source), 0o644); err != nil {
		t.Fatalf("write proto fixture: %v", err)
	}
}

func writeDescribeAPIProtoFixture(t *testing.T, dir string) {
	t.Helper()

	protoPath := filepath.Join(dir, "api", "v1", "echo.proto")
	if err := os.MkdirAll(filepath.Dir(protoPath), 0o755); err != nil {
		t.Fatalf("mkdir proto dir: %v", err)
	}

	const source = `syntax = "proto3";

package test.v1;

// Echo responds with the request payload for api/v1 describe generation tests.
service Echo {
  // Ping echoes the inbound message.
  rpc Ping(PingRequest) returns (PingResponse);
}

message PingRequest {
  string message = 1;
}

message PingResponse {
  string message = 1;
}
`
	if err := os.WriteFile(protoPath, []byte(source), 0o644); err != nil {
		t.Fatalf("write proto fixture: %v", err)
	}
}

func compilationModuleFile(t *testing.T) string {
	t.Helper()

	return "module example.com/describecompile\n\ngo 1.25.1\n\nrequire github.com/organic-programming/go-holons v0.0.0\n\nreplace github.com/organic-programming/go-holons => " + filepath.ToSlash(filepath.Join(holonsRepoRoot(t), "sdk", "go-holons")) + "\n"
}

func sampleDescribeResponse() *holonsv1.DescribeResponse {
	return &holonsv1.DescribeResponse{
		Manifest: &holonsv1.HolonManifest{
			Identity: &holonsv1.HolonManifest_Identity{
				Schema:     "holon/v1",
				Uuid:       "sample-uuid",
				GivenName:  "Sample",
				FamilyName: "Holon",
				Motto:      "Compile-time describe response.",
				Composer:   "test",
				Status:     "draft",
				Born:       "2026-03-23",
				Version:    "1.2.3",
				Aliases:    []string{"sample-holon"},
			},
			Description: "Sample describe response used to compile the Go template output.",
			Lang:        "go",
			Skills: []*holonsv1.HolonManifest_Skill{{
				Name:        "echo",
				Description: "Echoes a payload back to the caller.",
				When:        "The caller needs a quick connectivity check.",
				Steps:       []string{"Call Ping with a message."},
			}},
			Kind: "native",
			Build: &holonsv1.HolonManifest_Build{
				Runner: "go-module",
				Main:   "./cmd/sample",
			},
			Requires: &holonsv1.HolonManifest_Requires{
				Commands: []string{"go"},
				Files:    []string{"go.mod"},
			},
			Artifacts: &holonsv1.HolonManifest_Artifacts{
				Binary: "sample-holon",
			},
			Sequences: []*holonsv1.HolonManifest_Sequence{{
				Name:        "ping-once",
				Description: "Ping the service once.",
				Params: []*holonsv1.HolonManifest_Sequence_Param{{
					Name:        "message",
					Description: "Message to echo.",
					Required:    true,
				}},
				Steps: []string{`op sample-holon Ping '{"message":"{{ .message }}"}'`},
			}},
		},
		Services: []*holonsv1.ServiceDoc{{
			Name:        "test.v1.Echo",
			Description: "Echoes request payloads.",
			Methods: []*holonsv1.MethodDoc{{
				Name:         "Ping",
				Description:  "Pings the service.",
				InputType:    "test.v1.PingRequest",
				OutputType:   "test.v1.PingResponse",
				ExampleInput: `{"message":"hello"}`,
				InputFields: []*holonsv1.FieldDoc{
					{
						Name:        "message",
						Type:        "string",
						Number:      1,
						Description: "Message to echo.",
						Label:       holonsv1.FieldLabel_FIELD_LABEL_OPTIONAL,
						Required:    true,
						Example:     `"hello"`,
					},
					{
						Name:         "labels",
						Type:         "map<string, test.v1.Label>",
						Number:       2,
						Description:  "Labels associated with the request.",
						Label:        holonsv1.FieldLabel_FIELD_LABEL_MAP,
						MapKeyType:   "string",
						MapValueType: "test.v1.Label",
						EnumValues: []*holonsv1.EnumValueDoc{
							{Name: "LABEL_UNSPECIFIED", Number: 0, Description: "Default label."},
							{Name: "LABEL_OK", Number: 1, Description: "Healthy label."},
						},
					},
					{
						Name:        "profile",
						Type:        "test.v1.Profile",
						Number:      3,
						Description: "Nested profile data.",
						Label:       holonsv1.FieldLabel_FIELD_LABEL_OPTIONAL,
						NestedFields: []*holonsv1.FieldDoc{{
							Name:        "display_name",
							Type:        "string",
							Number:      1,
							Description: "Display name.",
							Label:       holonsv1.FieldLabel_FIELD_LABEL_OPTIONAL,
						}},
					},
				},
				OutputFields: []*holonsv1.FieldDoc{{
					Name:        "message",
					Type:        "string",
					Number:      1,
					Description: "Echoed message.",
					Label:       holonsv1.FieldLabel_FIELD_LABEL_OPTIONAL,
				}},
			}},
		}},
	}
}
